import type { GenerationType, GripType, Rarity, AccessoryType } from './types';

export const GENERATION_TYPES: GenerationType[] = [
  'Forma de Respiração',
  'Arma',
  'Acessório',
  'Missão',
  'Inimigo/Oni',
  'Kekkijutsu',
  'Classe/Origem',
  'Caçador',
  'Híbrido Humano-Oni',
  'NPC',
];

export const BREATHING_STYLES: string[] = [
  'Respiração da Água',
  'Respiração do Amor',
  'Respiração da Aranha',
  'Respiração da Areia',
  'Respiração da Besta',
  'Respiração do Sangue',
  'Respiração da Cerejeira',
  'Respiração das Chamas',
  'Respiração dos Sonhos',
  'Respiração da Flor',
  'Respiração da Grama',
  'Respiração do Inseto',
  'Respiração do Ferro',
  'Respiração da Lua',
  'Respiração da Névoa',
  'Respiração da Neve',
  'Respiração da Pedra',
  'Respiração da Raposa',
  'Respiração do Relampago',
  'Respiração da Serpente',
  'Respiração do Sol',
  'Respiração das Sombras',
  'Respiração do Som',
  'Respiração do Tempestade',
  'Respiração do Tigre',
  'Respiração do Trovão',
  'Respiração do Vagalume',
  'Respiração do Vento',
];

export const WEAPON_TYPES: string[] = [
  'Alabarda',
  'Arco Composto',
  'Arco Longo',
  'Arco Longo (Yumi)',
  'Arma do Espírito',
  'Bacalhau (Mace)',
  'Báculo',
  'Baioneta',
  'Balas de Ultravioleta',
  'Balestra',
  'Balestra de Repetição',
  'Bastão Retrátil',
  'Bō',
  'Bō Segmentado',
  'Chakram',
  'Chicote',
  'Cimitarra',
  'Cutelos Gêmeos',
  'Dao (Sabre Chinês)',
  'Double Blade',
  'Escopeta Cano Duplo',
  'Escudo de Batalha',
  'Espada de Lumen',
  'Espada de Sion',
  'Espada Longa',
  'Espada Ondular',
  'Faca Bowie',
  'Foice',
  'Fuuma Shuriken',
  'Guandao (Alabarda Chinesa)',
  'Hook Shuang',
  'Hwando (Sabre Coreano)',
  'Hwandudaedo (Espada Coreana)',
  'Ioiô de Lâmina',
  'Jambiya',
  'Jian (Espada Chinesa Reta)',
  'Kama',
  'Kanabō',
  'Katana',
  'Katana chicote',
  'Katana Ferrão',
  'Katana Serrilhada',
  'Kunai',
  'Kusarigama',
  'Lança (Rumh)',
  'Machado de Batalha',
  'Macuahuitl',
  'Manoplas / Soqueiras',
  'Montante',
  'Nagamaki',
  'Naginata',
  'Ngalo',
  'Nichirin Blades (Variadas)',
  'Nodachi/Ōdachi',
  'Nunchaku',
  'Ono & Mangual',
  'Ōtsuchi',
  'Pistolas Automáticas Híbridas',
  'Punho de Aço',
  'Qiang (Lança Chinesa)',
  'Rapieira',
  'Revólver',
  'Rifle',
  'Rifle Murata',
  'runkah',
  'Shamshir',
  'Shotel',
  'Shuriken',
  'Sicrimos',
  'Tantō',
  'Tepoztopilli',
  'Tessen',
  'Tetsubo',
  'Tomahawk',
  'Wakizashi',
  'Woldo (Alabarda Coreana)',
  'Yari',
  'Zweihänder',
];

export const GRIP_TYPES: GripType[] = [
  'Ittō-ryū',
  'Nitō-ryū',
  'Ryōtō',
  'Battōjutsu',
  'Kyūdō',
  'Taijutsu',
];

export const THEMATIC_TONES: string[] = [
  'Sombrio', 'Épico', 'Cômico', 'Misterioso', 'Heroico', 'Trágico'
];

export const ERAS: string[] = [
  'Período Edo (Japão Feudal)',
  'Cyberpunk',
  'Medieval Fantasia',
  'Steampunk',
  'Biopunk',
  'Moderno',
  'Futurista (Sci-Fi)',
  'Tempos Atuais',
  'Pós-apocalíptico',
];

export const RARITIES: Rarity[] = ['Low', 'Mid', 'High', 'Peça-lendária'];

export const ACCESSORY_TYPES: AccessoryType[] = ['Kimono', 'Brinco', 'Pulseira', 'Bainha', 'Haori'];

export const KEKKIJUTSU_TYPES: string[] = [
  'Manipulação de Sangue',
  'Criação de Gelo',
  'Teias de Aranha',
  'Fios Cortantes',
  'Ilusões Mortais',
  'Explosões de Sangue',
  'Manipulação de Ossos',
  'Controle de Plantas Venenosas',
  'Absorção de Vida',
  'Sombras Vivas',
  'Metamorfose Corporal',
  'Cristalização',
  'Gravitocinese',
  'Pirocinese Negra',
];