// FIX: Populated with full constant definitions to resolve module errors.
import type { Category, Rarity, Era, Tone, FilterState } from './types';
import { ORIGINS_DATA } from './lib/originsData';

export const CATEGORIES: Category[] = [
    'Caçador', 'Inimigo/Oni', 'NPC', 'Arma', 'Acessório', 'Forma de Respiração', 'Kekkijutsu', 'Local/Cenário', 'Missão/Cenário', 'World Building'
];

export const RARITIES: Rarity[] = ['Aleatória', 'Comum', 'Incomum', 'Raro', 'Épico', 'Lendário', 'Amaldiçoado'];

export const ERAS: Era[] = [
    'Aleatória',
    'Período Edo (Japão Feudal)',
    'Medieval Fantasia',
    'Steampunk',
    'Cyberpunk',
    'Pós-apocalíptico',
    'Tempos Atuais',
    'Futurista (Sci-Fi)',
    'Biopunk'
];

export const TONES: Tone[] = ['épico', 'sombrio', 'misterioso', 'aventuresco', 'cômico', 'trágico', 'esperançoso'];

export const DEMON_BLOOD_ARTS: string[] = [
    'Aleatória', 'Manipulação de Sangue', 'Fios de Seda', 'Tambores de Impacto', 'Flechas Vetoriais', 'Teias de Aranha', 'Ilusões Mortais', 'Sonhos Manipulados', 'Absorção de Poder', 'Crioquinese', 'Pirocinese', 'Regeneração Acelerada', 'Clones de Carne', 'Manipulação de Esporos', 'Venenos e Toxinas'
];

export const PERSONALITIES: string[] = [
    'Aleatória', 'Honrado', 'Sombrio', 'Caótico', 'Leal', 'Enganador', 'Corajoso', 'Covarde', 'Sábio', 'Tolo', 'Arrogante', 'Humilde', 'Vingativo', 'Piedoso'
];

export const METAL_COLORS: string[] = [
    'Aleatória', 'Preto (Absorção Solar)', 'Vermelho (Chamas)', 'Amarelo (Trovão)', 'Azul (Água)', 'Verde (Vento)', 'Rosa (Amor)', 'Cinza (Besta)', 'Branco (Névoa)', 'Lavanda (Serpente)', 'Índigo (Som)'
];

export const COUNTRIES: string[] = [
    'Aleatório',
    'Afeganistão',
    'África do Sul',
    'Albânia',
    'Alemanha',
    'Angola',
    'Arábia Saudita',
    'Argélia',
    'Argentina',
    'Armênia',
    'Austrália',
    'Áustria',
    'Bahamas',
    'Bangladesh',
    'Barbados',
    'Barein',
    'Bélgica',
    'Belize',
    'Benim',
    'Bielorrússia',
    'Bolívia',
    'Bósnia e Herzegovina',
    'Botsuana',
    'Brasil',
    'Brunei',
    'Bulgária',
    'Burkina Faso',
    'Burundi',
    'Butão',
    'Cabo Verde',
    'Camarões',
    'Camboja',
    'Canadá',
    'Catar',
    'Cazaquistão',
    'Chade',
    'Chile',
    'China',
    'Chipre',
    'Cingapura',
    'Colômbia',
    'Comores',
    'Congo',
    'Coreia do Norte',
    'Coreia do Sul',
    'Costa do Marfim',
    'Costa Rica',
    'Croácia',
    'Cuba',
    'Dinamarca',
    'Djibuti',
    'Dominica',
    'Egito',
    'El Salvador',
    'Emirados Árabes Unidos',
    'Equador',
    'Eritreia',
    'Eslováquia',
    'Eslovênia',
    'Espanha',
    'Estados Unidos',
    'Estônia',
    'Eswatini (Suazilândia)',
    'Etiópia',
    'Fiji',
    'Filipinas',
    'Finlândia',
    'França',
    'Gabão',
    'Gâmbia',
    'Gana',
    'Geórgia',
    'Granada',
    'Grécia',
    'Guatemala',
    'Guiana',
    'Guiné',
    'Guiné Equatorial',
    'Guiné-Bissau',
    'Haiti',
    'Honduras',
    'Hungria',
    'Iêmen',
    'Ilhas Marechal',
    'Ilhas Salomão',
    'Índia',
    'Indonésia',
    'Irã',
    'Iraque',
    'Irlanda',
    'Islândia',
    'Israel',
    'Itália',
    'Jamaica',
    'Japão',
    'Jordânia',
    'Kiribati',
    'Kuwait',
    'Laos',
    'Lesoto',
    'Letônia',
    'Líbano',
    'Libéria',
    'Líbia',
    'Liechtenstein',
    'Lituânia',
    'Luxemburgo',
    'Madagascar',
    'Malásia',
    'Malaui',
    'Maldivas',
    'Mali',
    'Malta',
    'Marrocos',
    'Maurícia',
    'Mauritânia',
    'México',
    'Mianmar (Birmânia)',
    'Micronésia',
    'Moçambique',
    'Moldávia',
    'Mônaco',
    'Mongólia',
    'Montenegro',
    'Namíbia',
    'Nauru',
    'Nepal',
    'Nicarágua',
    'Níger',
    'Nigéria',
    'Noruega',
    'Nova Zelândia',
    'Omã',
    'Países Baixos (Holanda)',
    'Palau',
    'Palestina',
    'Panamá',
    'Papua-Nova Guiné',
    'Paquistão',
    'Paraguai',
    'Peru',
    'Polônia',
    'Portugal',
    'Quênia',
    'Quirguistão',
    'Reino Unido',
    'República Centro-Africana',
    'República Democrática do Congo',
    'República Dominicana',
    'República Tcheca',
    'Romênia',
    'Ruanda',
    'Rússia',
    'Samoa',
    'San Marino',
    'Santa Lúcia',
    'São Cristóvão e Névis',
    'São Tomé e Príncipe',
    'São Vicente e Granadinas',
    'Seicheles',
    'Senegal',
    'Serra Leoa',
    'Sérvia',
    'Síria',
    'Somália',
    'Sri Lanka',
    'Sudão',
    'Sudão do Sul',
    'Suécia',
    'Suíça',
    'Suriname',
    'Tailândia',
    'Tajiquistão',
    'Tanzânia',
    'Timor-Leste',
    'Togo',
    'Tonga',
    'Trinidad e Tobago',
    'Tunísia',
    'Turcomenistão',
    'Turquia',
    'Tuvalu',
    'Ucrânia',
    'Uganda',
    'Uruguai',
    'Uzbequistão',
    'Vanuatu',
    'Vaticano',
    'Venezuela',
    'Vietnã',
    'Zâmbia',
    'Zimbábue',
];

export const TERRAINS: string[] = [
    'Aleatória', 'Floresta Densa', 'Montanhas Rochosas', 'Pântano Nebuloso', 'Cidade Assombrada', 'Templo Antigo', 'Caverna de Cristal', 'Vulcão Ativo', 'Planície Nevada', 'Deserto de Areia Negra'
];

export const THREAT_SCALES: string[] = [
    'Aleatória', 'Conflito Local', 'Guerra Regional', 'Ameaça Nacional', 'Crise Continental', 'Perigo Global', 'Evento de Extinção'
];

export const ONI_POWER_LEVELS: string[] = [
    'Aleatório', 'Oni Comum', 'Oni de Elite', 'Lua Inferior', 'Lua Superior', 'Classe Muzan'
];

// FIX: Added ORIGINS export by deriving it from ORIGINS_DATA to resolve import error.
export const ORIGINS: string[] = ['Aleatória', ...ORIGINS_DATA.map(o => o.nome)];

export const INITIAL_FILTERS: FilterState = {
    category: '',
    // Hunter
    hunterEra: 'Aleatória',
    hunterCountry: 'Aleatório',
    hunterOrigin: 'Aleatória',
    hunterArchetype: 'Aleatória',
    hunterPersonality: 'Aleatória',
    hunterWeapon: 'Aleatório',
    hunterBreathingStyles: [],
    hunterAccessory: 'Aleatório',
    // Oni
    oniPowerLevel: 'Aleatório',
    oniCountry: 'Aleatório',
    oniWeapon: 'Aleatório',
    oniInspirationKekkijutsu: [],
    oniInspirationBreathing: 'Nenhuma',
    oniPersonality: 'Aleatória',
    oniEra: 'Aleatória',
    // NPC
    npcEra: 'Aleatória',
    npcCountry: 'Aleatório',
    npcOrigin: 'Aleatória',
    npcProfession: 'Aleatória',
    npcPersonality: 'Aleatória',
    npcWeapon: 'Aleatório',
    npcAccessory: 'Nenhum',
    // Weapon
    weaponRarity: 'Aleatória',
    weaponEra: 'Aleatória',
    weaponCountry: 'Aleatório',
    weaponType: 'Aleatório',
    weaponMetalColor: 'Aleatório',
    // Accessory
    accessoryRarity: 'Aleatória',
    accessoryEra: 'Aleatória',
    accessoryOrigin: 'Aleatória',
    accessoryCountry: 'Aleatório',
    accessoryBreathingInspiration: 'Nenhuma',
    accessoryKekkijutsuInspiration: 'Nenhuma',
    accessoryWeaponInspiration: 'Nenhuma',
    // Breathing Form
    baseBreathingStyles: [],
    breathingFormEra: 'Aleatória',
    breathingFormCountry: 'Aleatório',
    breathingFormOrigin: 'Aleatória',
    breathingFormTone: 'épico',
    breathingFormWeapon: 'Aleatório',
    breathingFormArchetype: 'Aleatória',
    // Kekkijutsu
    kekkijutsuEra: 'Aleatória',
    kekkijutsuCountry: 'Aleatório',
    kekkijutsuKekkijutsuInspiration: 'Aleatória',
    kekkijutsuBreathingInspiration: 'Nenhuma',
    kekkijutsuWeaponInspiration: 'Nenhuma',
    kekkijutsuAccessoryInspiration: 'Nenhuma',
    // Location
    locationTone: 'misterioso',
    locationEra: 'Aleatória',
    locationCountry: 'Aleatório',
    locationTerrain: 'Aleatório',
    // Mission
    missionTone: 'sombrio',
    intensity: 3,
    missionScale: 'local',
    protagonist: '',
    targets: '',
    moodModifiers: '',
    // World Building
    wbTone: 'épico',
    wbEra: 'Aleatória',
    wbCountry: 'Aleatório',
    wbThreatScale: 'Aleatória',
    wbLocation: '',
};