import type { Tematica } from '../types';

export const TEMATICAS_DATA: { value: Tematica; label: string }[] = [
    { value: 'Aleatória', label: 'Aleatória' },
    { value: 'Período Edo (Japão Feudal)', label: 'Período Edo (Japão Feudal)' },
    { value: 'Medieval Fantasia', label: 'Medieval Fantasia' },
    { value: 'Steampunk', label: 'Steampunk' },
    { value: 'Cyberpunk', label: 'Cyberpunk' },
    { value: 'Pós-apocalíptico', label: 'Pós-apocalíptico' },
    { value: 'Moderno', label: 'Moderno' },
    { value: 'Tempos Atuais', label: 'Tempos Atuais' },
    { value: 'Futurista (Sci-Fi)', label: 'Futurista (Sci-Fi)' },
    { value: 'Biopunk', label: 'Biopunk' },
    { value: 'Shogunato Cibernético', label: 'Shogunato Cibernético' },
    { value: 'DOS CAÇADORES DE SOMBRAS', label: 'DOS CAÇADORES DE SOMBRAS' },
    { value: '⚔️ DOS DEUSES CAÍDOS', label: '⚔️ DOS DEUSES CAÍDOS' },
    { value: '🕵️‍♂️ DO JAZZ & OCULTISMO', label: '🕵️‍♂️ DO JAZZ & OCULTISMO' },
    { value: '⚗️ DA REVOLUÇÃO INDUSTRIAL OCULTA', label: '⚗️ DA REVOLUÇÃO INDUSTRIAL OCULTA' },
    { value: '🤠 VELHO OESTE SOLAR', label: '🤠 VELHO OESTE SOLAR' },
    { value: '🏴‍☠️ DOS IMPÉRIOS FLUTUANTES', label: '🏴‍☠️ DOS IMPÉRIOS FLUTUANTES' },
    { value: '🏜️ DO SAARA ETERNO', label: '🏜️ DO SAARA ETERNO' },
    { value: '🎭 DOS CINCO REINOS (WUXIA/XIANXIA)', label: '🎭 DOS CINCO REINOS (WUXIA/XIANXIA)' },
    { value: '🧙 DA ALVORADA ANCESTRAL', label: '🧙 DA ALVORADA ANCESTRAL' },
    { value: '🧬 DO JARDIM PROIBIDO (BIOPUNK ORGÂNICO)', label: '🧬 DO JARDIM PROIBIDO (BIOPUNK ORGÂNICO)' },
    { value: 'Neon-Noir Megacidade', label: 'Neon-Noir Megacidade' },
    { value: '💠 DA INFOCRACIA', label: '💠 DA INFOCRACIA' },
    { value: '🌃 DO RENASCIMENTO SOMBRIO', label: '🌃 DO RENASCIMENTO SOMBRIO' },
    { value: '🌃 DO SUBMUNDO NOTURNO', label: '🌃 DO SUBMUNDO NOTURNO' },
    { value: 'Mythpunk Amazônico', label: 'Mythpunk Amazônico' },
    { value: 'Ártico Steampunk', label: 'Ártico Steampunk' },
    { value: '🌌 DOS CINZÁRIOS (PÓS-APOCALÍPTICO MÍSTICO)', label: '🌌 DOS CINZÁRIOS (PÓS-APOCALÍPTICO MÍSTICO)' },
    { value: '🧟 DA QUEDA DOS REINOS', label: '🧟 DA QUEDA DOS REINOS' },
    { value: '🤖 DA SINGULARIDADE (PÓS-HUMANA)', label: '🤖 DA SINGULARIDADE (PÓS-HUMANA)' },
];